#!/bin/bash
echo $(awk '/^cpu /{print "previdle=" $3 "; prevtotal=" $2+$3 }' /proc/stat); sleep 0.4; eval $(awk '/^cpu /{print "idle=" $3 "; total=" $2+$3 }' /proc/stat); intervaltotal=$((total-${prevtotal:-0})); echo "$((100*( (intervaltotal) - ($idle-${previdle:-0}) ) / (intervaltotal) ))
