#!/bin/bash
cpu=$(top -b -n2 -p 1 | fgrep "Cpu(s)" | tail -1 | awk -F'id,' -v prefix="$prefix" '{ split($1, vs, ","); v=vs[length(vs)]; sub("%", "", v); printf "%s%.0f\n", prefix, 100 - v }')
if [[ $cpu -gt 90 ]]; then
	cpu=$(~/scripts/pp 1 $cpu)
elif [[ $cpu -gt 75 ]]; then
	cpu=$(~/scripts/pp 3 $cpu)
fi
echo $(~/scripts/pp 12 cpu)$(~/scripts/pp 8 :)$cpu
